#%RAML 0.8
---
title: API Resource
baseUri: https://localhost/api/
protocols: [HTTPS]
mediaType: application/json

traits:
  - auth: !include _traits/auth.raml

/users:
  description: User resource.
  get:
    is: [auth: { roles: 'staff' }]
    description: Retrive the list of the users.
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "firstname": "Romain",
                  "lastname": "Terieur",
                  "phone": "+6624582",
                  "roles": [
                    "citizen"
                  ]
                },
                {
                  "id": "54d8ae163fd30364605c81a9",
                  "firstname": "Romain",
                  "lastname": "Terieur",
                  "phone": "+8211332",
                  "roles": [
                    "citizen",
                    "staff"
                  ]
                },
                ...
              ]
  post:
    description: Create a new user.
    body:
      application/json:
        example: |
          {
            "firstname": "Romain",
            "lastname": "Terieur",
            "phone": "+6624582",
            "roles": [
              "citizen"
            ]
          }
    responses:
      201:
        body:
          application/json:
            example: |
              {
                "id": "54d8ae163fd30364605c81a4",
                "firstname": "Romain",
                "lastname": "Terieur",
                "phone": "+6624582",
                "roles": [
                  "citizen"
                ]
              }

  /{id}:
    get:
      is: [auth: {roles: 'any'} ]
      description: Retrieve the details of a specific user.
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "firstname": "Romain",
                  "lastname": "Terieur",
                  "phone": "+6624582",
                  "roles": [
                    "citizen"
                  ]
                }
    put:
      is: [auth: {roles: 'staff'} ]
      description: Update the details of a specific user.
      body:
        application/json:
          example: |
            {
              "firstname": "Romain",
              "lastname": "Terieur",
              "phone": "+6624582",
              "roles": [
                "citizen"
              ]
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "firstname": "Romain",
                  "lastname": "Terieur",
                  "phone": "+6624582",
                  "roles": [
                    "citizen"
                  ]
                }
    delete:
      is: [auth: {roles: 'staff'} ]
      description: Delete a specific user.
      responses:
        204:
          body:

/issue:

  get:
    description: Retrieve the list of the issues.
    responses:
      200:
        body:
          application/json:
            example: |
             {  
                "id": "ds9a7d9sa7d9sa8d,"
                "_author":
                { 
                  "id": "asd8sad97asd8ahdas987ads",
                  "firstname": "Romain",
                  "lastname": "Terieur"
                },
                "_issueType":
                { 
                  "id": "dsa9d8sa09d809sa8das",
                  "name": "Hole in a road",
                  "description": "lorem ipsum"
                  },
                "description": "issue's description",
                "longitude": "24",
                "latitude": "12",
                "status": "issue's status",
                "_comments":
                [{
                  "id": "32kjlkjlkjl321",
                  "_author":
                  { 
                    "id": "28312hkhkh321",
                    "firstname": "Matthieu",
                    "lastname": "Harbich"
                  },
                  "date": "3w3qweq",
                  "content": "lorem ipsum"
                },
                {
                  "id": "32kjlkjlkjl321",
                  "_author":
                  { 
                    "id": "28312hkhkh321",
                    "firstname": "Matthieu",
                    "lastname": "Harbich"
                  },
                  "date": "3w3qweq",
                  "content": "lorem ipsum"
                }]
              }

  post:
    description: Create a new issue.
    body:
      application/json:
        example: |
          {  
                "author":
                { 
                  "firstname": "Romain",
                  "lastname": "Terieur"
                },
                "issueType":
                { 
                  "name": "Hole in a road",
                  "description": "lorem ipsum"
                  },
                "description": "issue's description",
                "longitude": "24",
                "latitude": "12",
                "status": "issue's status",
                "comments":
                [{
                  "author":
                  { 
                    "firstname": "Matthieu",
                    "lastname": "Harbich"
                  },
                  "date": "3w3qweq",
                  "content": "lorem ipsum"
                },
                {
                  "author":
                  { 
                    "firstname": "Matthieu",
                    "lastname": "Harbich"
                  },
                  "date": "3w3qweq",
                  "content": "lorem ipsum"
                }]
              }
    responses:
      201:
        body:
          application/json:
            example: |
              {  
                "id": "ds9a7d9sa7d9sa8d,"
                "_author":
                { 
                  "id": "asd8sad97asd8ahdas987ads",
                  "firstname": "Romain",
                  "lastname": "Terieur"
                },
                "_issueType":
                { 
                  "id": "dsa9d8sa09d809sa8das",
                  "name": "Hole in a road",
                  "description": "lorem ipsum"
                  },
                "description": "issue's description",
                "longitude": "24",
                "latitude": "12",
                "status": "issue's status",
                "_comments":
                [{
                  "id": "32kjlkjlkjl321",
                  "_author":
                  { 
                    "id": "28312hkhkh321",
                    "firstname": "Matthieu",
                    "lastname": "Harbich"
                  },
                  "date": "3w3qweq",
                  "content": "lorem ipsum"
                },
                {
                  "id": "32kjlkjlkjl321",
                  "_author":
                  { 
                    "id": "28312hkhkh321",
                    "firstname": "Matthieu",
                    "lastname": "Harbich"
                  },
                  "date": "3w3qweq",
                  "content": "lorem ipsum"
                }]
              }
  /{id}:
    get:
      description: Get an issue by his ID.
      responses:
        200:
          body:
            application/json:
              example: |
               {  
                  "id": "ds9a7d9sa7d9sa8d,"
                  "_author":
                  { 
                    "id": "asd8sad97asd8ahdas987ads",
                    "firstname": "Romain",
                    "lastname": "Terieur"
                  },
                  "_issueType":
                  { 
                    "id": "dsa9d8sa09d809sa8das",
                    "name": "Hole in a road",
                    "description": "lorem ipsum"
                    },
                  "description": "issue's description",
                  "longitude": "24",
                  "latitude": "12",
                  "status": "issue's status",
                  "_comments":
                  [{
                    "id": "32kjlkjlkjl321",
                    "_author":
                    { 
                      "id": "28312hkhkh321",
                      "firstname": "Matthieu",
                      "lastname": "Harbich"
                    },
                    "date": "3w3qweq",
                    "content": "lorem ipsum"
                  },
                  {
                    "id": "32kjlkjlkjl321",
                    "_author":
                    { 
                      "id": "28312hkhkh321",
                      "firstname": "Matthieu",
                      "lastname": "Harbich"
                    },
                    "date": "3w3qweq",
                    "content": "lorem ipsum"
                  }]
                } 
    put:
      description: Update the details of a specific issue.
      body:
        application/json:
          example: |
            {  
                "description": "issue's description",
                "longitude": "24",
                "latitude": "12"
              }

      responses: 
        200:
          body:
            application/json:
              example: |
                {  
                  "id": "ds9a7d9sa7d9sa8d,"
                  "_author":
                  { 
                    "id": "asd8sad97asd8ahdas987ads",
                    "firstname": "Romain",
                    "lastname": "Terieur"
                  },
                  "_issueType":
                  { 
                    "id": "dsa9d8sa09d809sa8das",
                    "name": "Hole in a road",
                    "description": "lorem ipsum"
                    },
                  "description": "issue's description",
                  "longitude": "24",
                  "latitude": "12",
                  "status": "issue's status",
                  "_comments":
                  [{
                    "id": "32kjlkjlkjl321",
                    "_author":
                    { 
                      "id": "28312hkhkh321",
                      "firstname": "Matthieu",
                      "lastname": "Harbich"
                    },
                    "date": "3w3qweq",
                    "content": "lorem ipsum"
                  },
                  {
                    "id": "32kjlkjlkjl321",
                    "_author":
                    { 
                      "id": "28312hkhkh321",
                      "firstname": "Matthieu",
                      "lastname": "Harbich"
                    },
                    "date": "3w3qweq",
                    "content": "lorem ipsum"
                  }]
                }
    delete:
      description: Delete a specific issue.
      responses:
        204:
          body:


  /{id}/actions:
    post:
      description: |
        Actions update the issue statu's.
        An action is an interaction that an user can have with your app.

        ## Actions

         * solve:
         * acknowledge:
         * assign an issue:
         * reject an issue:
         * take an issue:
         * add a comment:

      body:
        application/json:
          example: |
            {
              "actionName": "solve - acknowledge - ..."
            }


      
          

 /issueType:
  description: issueType resource.
  get:
    is: [auth: { roles: 'staff' }]
    description: Retrieve the list of the issue types.
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "name": "Graffiti",
                  "description": "There is a graffiti somewhere"
                },
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "name": "Broken Street Light",
                  "description": "There is a broken streetlight somewhere"
                }
              ]
  post:
    description: Create a new issueType.
    body:
      application/json:
        example: |
          {
            "name": "Broken sidewalk",
            "description": "There is a broken sidewalk in the city"
          }
    responses:
      201:
        body:
          application/json:
            example: |
              {
                "id": "54d8ae163fd30364605c81a4",
                "name": "Broken sidewalk",
                "description": "There is a broken sidewalk in the city",
                }

  /{id}:
    get:
      is: [auth: {roles: 'any'} ]
      description: Retrieve the details of a specific issueType.
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "name": "Broken sidewalk",
                  "description": "There is a broken sidewalk in the city"
                }
    put:
      is: [auth: {roles: 'staff'} ]
      description: Update the details of a specific issueType.
      body:
        application/json:
          example: |
            {
              "name": "Broken sidewalk",
              "description": "There is a broken sidewalk in the city",
            }
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "id": "54d8ae163fd30364605c81a4",
                  "name": "Broken sidewalk",
                  "description": "There is a broken sidewalk in the city"
                }
    delete:
      is: [auth: {roles: 'staff'} ]
      description: Delete a specific issueType.
      responses:
        204:
          body:
